# -*- coding: utf-8 -*-
"""Lab1-C05315.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sYBkErOd5v_JOGDuul0sA0HjqnmI-pCW
"""

# Importación de las bibliotecas necesarias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Generación de datos sintéticos con variables diferentes
np.random.seed(0)  # Para reproducibilidad
habitaciones = np.random.randint(1, 6, size=(100, 1))  # Número de habitaciones
precio = (habitaciones * 100) + (np.random.rand(100, 1) * 100)  # Precio de las viviendas en miles de dólares

# Convertir los datos a un DataFrame de pandas
datos = pd.DataFrame(data=np.hstack((habitaciones, precio)), columns=['Habitaciones', 'Precio'])

# Visualización de los datos
plt.scatter(datos['Habitaciones'], datos['Precio'])
plt.xlabel('Número de Habitaciones')
plt.ylabel('Precio (mil $)')
plt.title('Precio de viviendas según el número de habitaciones')
plt.show()

# División del dataset en conjunto de entrenamiento y de prueba
X = datos[['Habitaciones']]  # Variable independiente
y = datos['Precio']  # Variable dependiente
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Creación y entrenamiento del modelo de regresión lineal
modelo = LinearRegression()
modelo.fit(X_train, y_train)

# Predicción de los valores para el conjunto de datos de prueba
predicciones = modelo.predict(X_test)

# Cálculo de métricas de rendimiento
mse = mean_squared_error(y_test, predicciones)
r2 = r2_score(y_test, predicciones)

print(f"Error Cuadrático Medio (MSE): {mse}")
print(f"Coeficiente de Determinación (R²): {r2}")

# Visualización de la línea de regresión sobre los datos de prueba
plt.scatter(X_test, y_test, color='black', label='Datos reales')
plt.plot(X_test, predicciones, color='blue', linewidth=3, label='Línea de regresión')
plt.xlabel('Número de Habitaciones')
plt.ylabel('Precio (mil $)')
plt.title('Regresión Lineal Simple')
plt.legend()
plt.show()